import "./globals.css";
import Header from '@/Components/Header'
import Cursor from '@/Components/Cursor'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Cursor/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
